# Generated by Django 5.0.3 on 2024-03-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=255)),
                ('AccountBalance', models.IntegerField()),
                ('CurrentBalance', models.CharField(max_length=20)),
            ],
        ),
    ]
